name: Build V2ray

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: init
        run: |
          # upx 3.95 for mips wait for 4.0 fix https://github.com/upx/upx/issues/342
          sudo apt-get update
          sudo apt-get install -y upx
          sudo rm -rf /usr/bin/go*
          sudo rm -rf /usr/local/go
          wget https://dl.google.com/go/go1.17.1.linux-amd64.tar.gz -O go.tar.gz
          sudo tar -C /usr/local -xzf go.tar.gz
          wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
          tar xf upx-3.96-amd64_linux.tar.xz
          mv upx-3.96-amd64_linux/upx .
          rm -rf upx-3.96-amd64_linux*
      - name: build
        run: |
          mkdir tmp
          mkdir bin
          # Do not use "--depth=1" due to tags
          git clone https://github.com/v2fly/v2ray-core.git
          cd v2ray-core
          git checkout tags/v4.44.0
          cd ..
          # sed -i 's/^\t_ "v2ray.com\/core\/main\/json"/\t\/\/ _ "v2ray.com\/core\/main\/json"/' v2ray-core/main/distro/all/all.go
          # sed -i 's/^\t\/\/ _ "v2ray.com\/core\/main\/jsonem"/\t_ "v2ray.com\/core\/main\/jsonem"/' v2ray-core/main/distro/all/all.go
          wget https://raw.githubusercontent.com/felix-fly/v2ray-openwrt/master/build.sh
          chmod +x ./build.sh
          ./build.sh linux mipsle
      - name: Upload artifact
        # uses: actions/upload-artifact@v2
        # with:
        #   name: build
        #   path: bin
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          name: V2ray-packages
          files: |
            bin/*.tar.gz
